"""empty message

Revision ID: 593afb09846c
Revises: 
Create Date: 2024-04-13 22:12:39.727987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593afb09846c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelname',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Date(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=False),
    sa.Column('destination_ip', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('source_port', sa.String(), nullable=False),
    sa.Column('destination_port', sa.String(), nullable=False),
    sa.Column('packet_length', sa.String(), nullable=False),
    sa.Column('flags', sa.String(), nullable=False),
    sa.Column('threat', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelname_id'), 'modelname', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modelname_id'), table_name='modelname')
    op.drop_table('modelname')
    # ### end Alembic commands ###
